name: Build and Deploy Web3 Apps

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to FTP
        # https://github.com/SamKirkland/FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/  # The directory containing your built React app
          server-dir: /www/1234.ch/web3-apps/  # Adjust to your desired remote directory
          clean-remote: true  # Optionally clean the remote directory before deployment
